version: '3.1'

services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .secrets.yml

  backend:
    container_name: backend
    image: node:21-alpine
    depends_on:
     - mongo
    restart: always
    ports:
      - 8080:8080
    working_dir: /home/node
    volumes:
      - ./Backend:/home/node
    env_file:
      - .secrets.yml
ยง    command: npm run start
