version: '3.1'

services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .secrets.yml

#  backend:
#    container_name: backend
#    platform: linux/amd64
#    image: node:lts-bullseye
#    depends_on:
#      - mongo
#    restart: on-failure # always
#    ports:
#      - "8080:8080"
#    working_dir: /home/node
#    volumes:
#      - ./Backend:/home/node
#    env_file:
#      - .secrets.yml
#    command:
#      - /bin/sh
#      - -c
#      - |
#        apt update
#        apt install ffmpeg -y
#        npm run docker:start
#
#
  frontend:
    container_name: frontend
    image: node:21-alpine
    depends_on:
      - backend
    restart: on-failure # always
    ports:
      - "3000:3000"
    working_dir: /home/node
    volumes:
      - ./Frontend:/home/node
    env_file:
      - .secrets.yml
    command: npm run docker:start

