version: '3.1'

services:
  mongo:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - .secrets.yml

  openvidu:
    image: openvidu/openvidu-dev:2.29.0 
    restart: on-failure # always
    ports:
      - "4443:4443"
    env_file:
      - ./Backend/.env-openvidu

  backend:
    container_name: backend
    image: node:21-alpine
    depends_on:
     - mongo
     - openvidu
    restart: on-failure # always
    ports:
      - "8080:8080"
    working_dir: /home/node
    volumes:
      - ./Backend:/home/node
    env_file:
      - .secrets.yml
    command: npm run docker:dev

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: on-failure # always
    ports:
      - "3000:3000"
    env_file:
      - .secrets.yml
    depends_on:
      - backend

