on:
  push:
  pull_request:
    branches:
      - main

jobs:
  jest-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: "Backend"
        run: npm ci
      - name: Run tests
        working-directory: "Backend"
        run: npm test
